version: '3'

services:
  weatherapp_backend:
    env_file: api_keys.env
    container_name: "weatherapp_backend"
    image: weatherapp_backend
    restart: always
    ports:
      - 9000:9000
  weatherapp_frontend:
    image: weatherapp_frontend
    restart: "always"
    ports:
      - 8000:8000
    environment:
      - ENDPOINT=weatherapp_backend:9000/api
